# Generated by Django 6.0.3 on 2026-03-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
